---
# Sample vars file
################################################################################
# Lab & cluster infrastrucutre vars
################################################################################
# Which lab to be deployed into (Ex scalelab)
lab:
# Which cloud in the lab environment (Ex cloud42)
lab_cloud:

# Either bm or rwn or sno
cluster_type:

# Applies to both bm/rwn clusters
worker_node_count:

# Versions are also controlled by what versions the assisted installer provides see
# "assisted_service_openshift_version" variable in default section of 
# bastion-assisted-installer role for which versions are currently available.
# Also for RWN deployment check ISO image version "rhcos_image" variable in default 
# section of generate-livecd role.
openshift_version: "4.8"
# Either OpenShiftSDN or OVNKubernetes
networktype: OpenShiftSDN

ssh_private_key_file: ~/.ssh/id_rsa
ssh_public_key_file: ~/.ssh/id_rsa.pub
pull_secret: "{{ lookup('file', '../pull_secret.txt') }}"

################################################################################
# Bastion node vars
################################################################################
bastion_cluster_config_dir: /root/{{ cluster_type }}

bastion_lab_interface: eno1np0
bastion_controlplane_interface: ens1f0

# vlaned interfaces are for remote worker node clusters only
bastion_vlaned_interface: ens1f1

# Generally this will be your bastion machine (if you run setup-bastion playbook)
assisted_installer_host: example.com
assisted_installer_port: 8090

# Generally this will be your bastion machine (if you run setup-bastion playbook)
http_store_host: example.com
http_store_port: 8080

http_store_path: /opt/http_store/data/

################################################################################
# OCP node vars
################################################################################
# Network configuration for bm cluster and rwn control-plane nodes
controlplane_lab_interface: eno1np0
controlplane_network_interface: ens1f0

# Network only for remote worker nodes
rwn_lab_interface: eno1np0
rwn_network_interface: ens1f1

